package com.brav.primisphoto.services;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 11/9/2017 10:47:15 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class FotoInoltrata implements KvmSerializable {
    
    public VectorByte foto;
    public String estensioneFoto;
    public int indiceFoto;
    public String numScheda;
    public String username;
    public String password;
    public String note;
    public String latitudine;
    public String longitudine;
    
    public FotoInoltrata(){}
    
    public FotoInoltrata(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("Foto"))
        {
            SoapPrimitive j = (SoapPrimitive)soapObject.getProperty("Foto");
            foto = new VectorByte(j);
        }
        if (soapObject.hasProperty("EstensioneFoto"))
        {
            Object obj = soapObject.getProperty("EstensioneFoto");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                estensioneFoto = j.toString();
            }else if (obj!= null && obj instanceof String){
                estensioneFoto = (String) obj;
            }
        }
        if (soapObject.hasProperty("IndiceFoto"))
        {
            Object obj = soapObject.getProperty("IndiceFoto");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                indiceFoto = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                indiceFoto = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("NumScheda"))
        {
            Object obj = soapObject.getProperty("NumScheda");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                numScheda = j.toString();
            }else if (obj!= null && obj instanceof String){
                numScheda = (String) obj;
            }
        }
        if (soapObject.hasProperty("Username"))
        {
            Object obj = soapObject.getProperty("Username");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                username = j.toString();
            }else if (obj!= null && obj instanceof String){
                username = (String) obj;
            }
        }
        if (soapObject.hasProperty("Password"))
        {
            Object obj = soapObject.getProperty("Password");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                password = j.toString();
            }else if (obj!= null && obj instanceof String){
                password = (String) obj;
            }
        }
        if (soapObject.hasProperty("Note"))
        {
            Object obj = soapObject.getProperty("Note");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                note = j.toString();
            }else if (obj!= null && obj instanceof String){
                note = (String) obj;
            }
        }

        if (soapObject.hasProperty("Latitudine"))
        {
            Object obj = soapObject.getProperty("Latitudine");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                password = j.toString();
            }else if (obj!= null && obj instanceof String){
                password = (String) obj;
            }
        }
        if (soapObject.hasProperty("Longitudine"))
        {
            Object obj = soapObject.getProperty("Longitudine");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                password = j.toString();
            }else if (obj!= null && obj instanceof String){
                password = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return foto.toString();
            case 1:
                return estensioneFoto;
            case 2:
                return indiceFoto;
            case 3:
                return numScheda;
            case 4:
                return username;
            case 5:
                return password;
            case 6:
                return note;
            case 7:
                return latitudine;
            case 8:
                return longitudine;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 9;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Foto";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "EstensioneFoto";
                break;
            case 2:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "IndiceFoto";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "NumScheda";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Username";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Password";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Note";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Latitudine";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Longitudine";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
