package com.brav.primisphoto.services;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 10/27/2017 1:25:58 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class Message implements KvmSerializable {
    
    public boolean ok;
    public String note;
    public int MaxLengthResponseNote;
    
    public Message(){}
    
    public Message(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("Ok"))
        {
            Object obj = soapObject.getProperty("Ok");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                ok = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                ok = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("Note"))
        {
            Object obj = soapObject.getProperty("Note");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                note = j.toString();
            }else if (obj!= null && obj instanceof String){
                note = (String) obj;
            }
        }
        if (soapObject.hasProperty("MaxLengthResponseNote"))
        {
            Object obj = soapObject.getProperty("MaxLengthResponseNote");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                MaxLengthResponseNote = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof String){
                MaxLengthResponseNote = (int) obj ;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return ok;
            case 1:
                return note;
            case 2:
                return MaxLengthResponseNote;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 2;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "Ok";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Note";
                break;
            case 2:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "MaxLengthResponseNote";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
